//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blobify.Uploader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blobify.Uploader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;zipRatios&gt;
        ///  &lt;zipRatio ext=&quot;PPTX&quot; ratio=&quot; 0.914272&quot;/&gt;
        ///  &lt;zipRatio ext=&quot;IDX&quot; ratio=&quot;0.899748&quot; /&gt;
        ///  &lt;zipRatio ext=&quot;RULESET&quot; ratio=&quot;0.884273&quot; /&gt;
        ///  &lt;zipRatio ext=&quot;PDF&quot; ratio=&quot;0.877303&quot; /&gt;
        ///  &lt;zipRatio ext=&quot;RESOURCES&quot; ratio=&quot;0.87017&quot; /&gt;
        ///  &lt;zipRatio ext=&quot;VSMDI&quot; ratio=&quot;0.858456&quot; /&gt;
        ///  &lt;zipRatio ext=&quot;CMD&quot; ratio=&quot;0.842994&quot; /&gt;
        ///  &lt;zipRatio ext=&quot;DATASOURCE&quot; ratio=&quot;0.830846&quot; /&gt;
        ///  &lt;zipRatio ext=&quot;OTF&quot; ratio=&quot;0.814566&quot; /&gt;
        ///  &lt;zipRatio ext=&quot;STYLECOP&quot; ratio=&quot;0.799465&quot; /&gt;
        ///  &lt;z [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZipRatios {
            get {
                return ResourceManager.GetString("ZipRatios", resourceCulture);
            }
        }
    }
}
