//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blobify.Shared.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blobify.Shared.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SOURCE:C:\Windows /REGEX:.txt$ /RECURSE /CONTAINER:files /PATH:AAA/BBB /LOGLEVEL:WARN.
        /// </summary>
        public static string GoodAllBlobifyArgs {
            get {
                return ResourceManager.GetString("GoodAllBlobifyArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /CONN:DefaultEndpointsProtocol=https;AccountName=someco;AccountKey=O21totdNsyxIgHMPIq0jVyBhjxkikfeVkOPfCzzdExvc9Yl4VxTXuC0VBfu275etxQnY/tzBqArmTwpoQyPn0w==;.
        /// </summary>
        public static string GoodConnNoLogLevelArgs {
            get {
                return ResourceManager.GetString("GoodConnNoLogLevelArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /CONN:DefaultEndpointsProtocol=https;AccountName=someco;AccountKey=O21totdNsyxIgHMPIq0jVyBhjxkikfeVkOPfCzzdExvc9Yl4VxTXuC0VBfu275etxQnY/tzBqArmTwpoQyPn0w==; /LOGLEVEL:WARN.
        /// </summary>
        public static string GoodConnWithLogLevelArgs {
            get {
                return ResourceManager.GetString("GoodConnWithLogLevelArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SOURCE:C:\Windows /CONTAINER:files.
        /// </summary>
        public static string GoodMinimalBlobifyArgs {
            get {
                return ResourceManager.GetString("GoodMinimalBlobifyArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /NOCONN.
        /// </summary>
        public static string GoodNoConnNoLogLevelArgs {
            get {
                return ResourceManager.GetString("GoodNoConnNoLogLevelArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /NOCONN /LOGLEVEL:WARN.
        /// </summary>
        public static string GoodNoConnWithLogLevelArgs {
            get {
                return ResourceManager.GetString("GoodNoConnWithLogLevelArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PARAMS:ParamsFiles\GoodAllBlobifyParams.txt.
        /// </summary>
        public static string GoodParamsArgs {
            get {
                return ResourceManager.GetString("GoodParamsArgs", resourceCulture);
            }
        }
    }
}
